/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String _kFontPkg = null;

  static const IconData shopping_cart_nv = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_outline_nv = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outline_nv = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz_outline_nv = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline_nv_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_nv = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_nv = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outline_nv = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_nv = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz_nv = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border_nv = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_border_nv = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_nv = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_shopping_cart_nv = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_nv = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_nv = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_checked = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData obscure_password = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giftcard = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_up_24_px = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_24_px = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_outline = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_shopping_cart_nv = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData added_shopping_cart_nv = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_outline_nv = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_card_nv = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_nv = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_error_nv = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle_outline_nv = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_nv = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_rotate_up_24_px = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_rotation_down_24_px = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData access_time_nv = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch_later_24_px = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_outline = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_high_24_px = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_low_24_px = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_fill = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData control = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_off = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_active = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show_password = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_cancel_fill = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_diagonal = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_export = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mall = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vertical = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_location = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_headline = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_outline = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley_face = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debit = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_forward = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
